.TH "src.GameMaster.ProtocolGameMaster.ProtocolGameMaster" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.GameMaster.ProtocolGameMaster.ProtocolGameMaster \- Протокол для мастера игры  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:Protocol\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "str \fBgenerate_answer\fP (self, str message)"
.br
.RI "Генерация ответа на сообщение игрока "
.ti -1c
.RI "Tuple[List[\fBCommandData\fP], str] \fBgenerate_instruction\fP (self, str message)"
.br
.RI "Генерация инструкций на основе сообщения "
.ti -1c
.RI "Tuple[str, Set[str]] \fBparse_commands\fP (self, List[\fBCommandData\fP] commands)"
.br
.RI "Обработка списка команд "
.ti -1c
.RI "Tuple[Optional[List[\fBCommandData\fP]], str] \fBvalidate_and_parse\fP (self, str input_text)"
.br
.RI "Валидация и парсинг входного текста "
.in -1c
.SH "Подробное описание"
.PP 
Протокол для мастера игры 

Определяет интерфейс для мастера игры, который отвечает за:
.IP "\(bu" 2
Генерацию ответов на действия игрока
.IP "\(bu" 2
Управление игровыми персонажами
.IP "\(bu" 2
Поддержание целостности игрового мира
.IP "\(bu" 2
Обработку команд и инструкций 
.PP

.PP
См\&. определение в файле \fBProtocolGameMaster\&.py\fP строка \fB4\fP
.SH "Методы"
.PP 
.SS " str src\&.GameMaster\&.ProtocolGameMaster\&.ProtocolGameMaster\&.generate_answer ( self, str message)"

.PP
Генерация ответа на сообщение игрока 
.PP
\fBАргументы\fP
.RS 4
\fImessage\fP Сообщение игрока 
.RE
.PP
\fBВозвращает\fP
.RS 4
str Ответ системы 
.RE
.PP

.PP
См\&. определение в файле \fBProtocolGameMaster\&.py\fP строка \fB18\fP
.SS " Tuple[List[\fBCommandData\fP], str] src\&.GameMaster\&.ProtocolGameMaster\&.ProtocolGameMaster\&.generate_instruction ( self, str message)"

.PP
Генерация инструкций на основе сообщения 
.PP
\fBАргументы\fP
.RS 4
\fImessage\fP Сообщение для обработки 
.RE
.PP
\fBВозвращает\fP
.RS 4
Tuple[List[\fBCommandData\fP], str] Кортеж из списка команд и текстового вывода 
.RE
.PP

.PP
См\&. определение в файле \fBProtocolGameMaster\&.py\fP строка \fB27\fP
.SS " Tuple[str, Set[str]] src\&.GameMaster\&.ProtocolGameMaster\&.ProtocolGameMaster\&.parse_commands ( self, List[\fBCommandData\fP] commands)"

.PP
Обработка списка команд 
.PP
\fBАргументы\fP
.RS 4
\fIcommands\fP Список команд для обработки 
.RE
.PP
\fBВозвращает\fP
.RS 4
Tuple[str, Set[str]] Кортеж из текстового вывода и множества имен активных персонажей 
.RE
.PP

.PP
См\&. определение в файле \fBProtocolGameMaster\&.py\fP строка \fB36\fP
.SS " Tuple[Optional[List[\fBCommandData\fP]], str] src\&.GameMaster\&.ProtocolGameMaster\&.ProtocolGameMaster\&.validate_and_parse ( self, str input_text)"

.PP
Валидация и парсинг входного текста 
.PP
\fBАргументы\fP
.RS 4
\fIinput_text\fP Текст для валидации и парсинга 
.RE
.PP
\fBВозвращает\fP
.RS 4
Tuple[Optional[List[\fBCommandData\fP]], str] Кортеж из списка команд (или None) и сообщения об ошибке 
.RE
.PP

.PP
См\&. определение в файле \fBProtocolGameMaster\&.py\fP строка \fB45\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для My Project из исходного текста\&.
