.TH "src.GameMaster.CommandData.CommandSelectCharacter" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.GameMaster.CommandData.CommandSelectCharacter \- Команда выбора персонажа для действия  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBsrc\&.GameMaster\&.CommandData\&.CommandData\fP\&.
.SH "Подробное описание"
.PP 
Команда выбора персонажа для действия 

Определяет, какой персонаж выполняет действие и какое именно действие он выполняет\&.

.PP
\fBАргументы\fP
.RS 4
\fIname\fP Имя персонажа 
.br
\fIaction\fP Описание действия 
.RE
.PP

.PP
См\&. определение в файле \fBCommandData\&.py\fP строка \fB29\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для My Project из исходного текста\&.
