.TH "src.GameMaster.GameMaster.PlayerDeathException" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.GameMaster.GameMaster.PlayerDeathException \- Исключение, возникающее при смерти игрового персонажа  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:Exception\&.
.SH "Подробное описание"
.PP 
Исключение, возникающее при смерти игрового персонажа 

Выбрасывается, когда игровой персонаж умирает, что приводит к завершению сессии и блокировке дальнейшего ввода\&. 
.PP
См\&. определение в файле \fBGameMaster\&.py\fP строка \fB18\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для My Project из исходного текста\&.
