.TH "src.GameMaster.CommandData.CommandCreateCharacter" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.GameMaster.CommandData.CommandCreateCharacter \- Команда создания нового персонажа  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBsrc\&.GameMaster\&.CommandData\&.CommandData\fP\&.
.SH "Подробное описание"
.PP 
Команда создания нового персонажа 

Используется для добавления нового персонажа в игру с заданным именем и описанием\&.

.PP
\fBАргументы\fP
.RS 4
\fIname\fP Имя нового персонажа 
.br
\fIdescription\fP Описание нового персонажа 
.RE
.PP

.PP
См\&. определение в файле \fBCommandData\&.py\fP строка \fB44\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для My Project из исходного текста\&.
