.TH "src.GameMaster.CommandData.CommandOffTopic" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.GameMaster.CommandData.CommandOffTopic \- Команда для обработки внеигрового ввода  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBsrc\&.GameMaster\&.CommandData\&.CommandData\fP\&.
.SH "Подробное описание"
.PP 
Команда для обработки внеигрового ввода 

Используется, когда ввод пользователя не относится к игровому процессу или нарушает правила игры\&. 
.PP
См\&. определение в файле \fBCommandData\&.py\fP строка \fB59\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для My Project из исходного текста\&.
