.TH "src.GameMaster.CommandData.CommandData" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.GameMaster.CommandData.CommandData \- Базовый класс для всех команд в игровой системе  

.SH SYNOPSIS
.br
.PP
.PP
Производные классы:\fBsrc\&.GameMaster\&.CommandData\&.CommandCreateCharacter\fP, \fBsrc\&.GameMaster\&.CommandData\&.CommandDataEnvironmentDescription\fP, \fBsrc\&.GameMaster\&.CommandData\&.CommandOffTopic\fP, \fBsrc\&.GameMaster\&.CommandData\&.CommandPlayerDeath\fP и \fBsrc\&.GameMaster\&.CommandData\&.CommandSelectCharacter\fP\&.
.SH "Подробное описание"
.PP 
Базовый класс для всех команд в игровой системе 

Используется как маркер для типизации команд и обеспечивает единый интерфейс для всех типов команд в системе\&. 
.PP
См\&. определение в файле \fBCommandData\&.py\fP строка \fB5\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для My Project из исходного текста\&.
