# Generated by Django 5.0.2 on 2025-04-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='game_session_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
