# Generated by Django 5.0.2 on 2025-04-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamesession_game_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sound_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
